samples: config/samples.tsv
units: config/units.tsv

dataset: 'Angola_aegypti'

ref:
  genome:
        "resources/reference/aedes-aegypti-lvpagwg_chromosomes.l5.fa"
  transcriptome:
        "resources/reference/aedes-aegypti-lvpagwg_transcripts.l5.fa"
  gtf: 
        "resources/reference/Aedes-aegypti-LVP_AGWG_BASEFEATURES_AaegL5.2.gtf"
  gff:
        "resources/reference/VectorBase-48_AaegyptiLVP_AGWG.gff"
  snpeffdb:
        "Aedes_aegypti_lvpagwg"
  genenames:
        "resources/gene_names.tsv"

# Chromosome names for the appropriate species. Should correspond to the reference fasta/gff files. 
chroms: ['1', '2', '3']

contrasts: [['ContAngola_FenAngola'], ['NewOrleans_ContAngola'], ['Rockefeller_ContAngola']]

# ploidy level for freebayes, as generally we are using pooled samples.
ploidy: 10

# If activate:True, creates allele balance .xlsx reports on IR mutations of choice
IRmutations: 
      activate: True
      path: "resources/IRmutations.tsv"

# Do we want to run pbs (Needs three conditions, two more closely related and a slight outgroup)
pbs:
      comparisons: [['FenAngola', 'ContAngola', 'NewOrleans'], ['FenAngola', 'ContAngola', 'Rockefeller']]
      activate: True