samples: config/samples.tsv
units: config/units.tsv

dataset: 'Angola_aegypti'

ref:
  genome:
        "resources/reference/aedes-aegypti-lvpagwg_chromosomes.l5.fa"
  transcriptome:
        "resources/reference/aedes-aegypti-lvpagwg_transcripts.l5.fa"
  gtf: 
        "resources/reference/Aedes-aegypti-LVP_AGWG_BASEFEATURES_AaegL5.2.gtf"
  gff:
        "resources/reference/VectorBase-48_AaegyptiLVP_AGWG.gff"
  snpeffdb:
        "Aedes_aegypti_lvpagwg"
  genenames:
        "resources/gene_names.tsv"

# Chromosome names for the appropriate species. Should correspond to the reference fasta/gff files. 
chroms: ['1', '2', '3']

# List of contrasts to do DE and Fst analysis on. Should correspond to the 'treatment' columns of the samples.tsv file, and be separated by an underscore "_". i.e ['control_case'], or ['Kisumu_Tiassale'].
contrasts:
      - 'ContAngola_FenAngola'
      - 'NewOrleans_ContAngola'
      - 'Rockefeller_ContAngola'

# Ploidy level for freebayes to call at. (Generally we are using pooled samples)
ploidy: 10

# If activate:True, creates allele balance .xlsx reports on IR mutations of choice
IRmutations: 
      activate: True
      path: "resources/IRmutations.tsv"

# Do we want to run pbs (Needs three conditions, two more closely related and a slight outgroup)
pbs:
      contrasts: [['FenAngola', 'ContAngola', 'NewOrleans'], ['FenAngola', 'ContAngola', 'Rockefeller']]
      activate: True

# For Anopheles gambiae s.l only - run Ancestry Informative Marker analysis.
AIMs:
      activate: True