samples: config/samples.tsv
units: config/units.tsv

# Dataset name
dataset: 'Ag_TiassAbo'

# Paths for reference files 
ref:
  genome:
        "resources/reference/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa"
  transcriptome:
        "resources/reference/Anopheles-gambiae-PEST_TRANSCRIPTS_AgamP4.12.fa"
  gtf: 
        "resources/reference/Anopheles-gambiae-PEST_BASEFEATURES_AgamP4.12.gtf"
  gff:
        "resources/reference/Anopheles-gambiae-PEST_BASEFEATURES_AgamP4.12.gff3"
  gaf:
        "resources/reference/VectorBase-50_AgambiaePEST_GO.gaf"
  snpeffdb:
        "Anopheles_gambiae"
  genenames:
        "resources/gene_names.tsv"

# Chromosome names for the appropriate species. Should correspond to the reference fasta/gff files. 
chroms: ['2L', '2R', '3L', '3R', 'X']

qc:
      activate: False

# List of contrasts to do DE and Fst analysis on. Should correspond to the 'treatment' columns of the samples.tsv file, and be separated by an underscore "_". i.e ['control_case'], or ['Kisumu_Tiassale'].
# The treatment names themselves must not contain underscores
contrasts:
      - 'ContAbo_DeltAbo'
      - 'ContAbo_MalaAbo'
      - 'ContAbo_PiriAbo'
      - 'ContTia_DeltTia'
      - 'ContTia_MalaTia'
      - 'ContTia_PiriTia'

progressiveGenes:
      activate: False
      groups: #"ContTia_DeltTia_MalaTia"

GSEA:
      activate: True
      KeggSpeciesID: "aga" # 3 letter KEGG species identifier
      replaceString: "AgaP_"


# Ploidy level for freebayes to call at. (Generally we are using pooled samples)
ploidy: 10
chunks: 9 # Number of chunks to split the genome into when parallelising freebayes

# If activate:True, creates allele balance .xlsx reports on IR mutations of choice
IRmutations: 
      activate: True
      path: "resources/IRmutations.tsv"

# Do we want to run pbs (Needs three conditions, two more closely related and a slight outgroup)
pbs:
      contrasts: [['DeltAbo', 'ContAbo', 'ContTia'], ['DeltTia', 'ContTia', 'ContAbo']]
      activate: True

# For Anopheles gambiae s.l only - run Ancestry Informative Marker analysis.
AIMs:
      activate: True
      missingness: 0.5                                # proportion between 0 and 1 
      gambcolu: "resources/gamb_vs_colu.zarr"         # path to gambcolu AIMs
      arab: "resources/gambcolu_vs_arab.zarr"         # path to arab AIMs
